# Generated by Django 6.1.1 on 2026-09-07 20:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', wagtail.fields.RichTextField(blank=True)),
                ('links', wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2)]], {})})),
                ('copyright', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Carrot&Claw', max_length=80)),
                ('menu', wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 1: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2)]], {})})),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Header',
            },
        ),
    ]
