# Generated by Django 6.1.1 on 2026-09-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='discord_url',
            field=models.URLField(blank=True, verbose_name='Discord'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='twitch_url',
            field=models.URLField(blank=True, verbose_name='Twitch'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube'),
        ),
    ]
