# Generated by Django 6.1.1 on 2026-09-08 20:44

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_footersettings_social_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHoursSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Show the open / closed badge in the site header.')),
                ('slots', wagtail.fields.StreamField([('slot', 3)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')]}), 1: ('wagtail.blocks.TimeBlock', (), {}), 2: ('wagtail.blocks.TimeBlock', (), {'help_text': 'Earlier than the opening time means the tavern stays open past midnight.'}), 3: ('wagtail.blocks.StructBlock', [[('day', 0), ('opens', 1), ('closes', 2)]], {})}, help_text='Times are server time (UTC). Add one entry per opening; a day can have several. Leave empty to hide the badge.')),
            ],
            options={
                'verbose_name': 'Opening hours',
            },
        ),
    ]
