# Generated by Django 6.1.1 on 2026-09-07 20:47

import django.db.models.deletion
import wagtail.fields
import wagtail_headless_preview.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('intro', models.CharField(blank=True, help_text='Short lead text under the title.', max_length=255)),
                ('body', wagtail.fields.StreamField([('hero', 7), ('rich_text', 8), ('image', 2), ('image_slider', 11), ('collapse', 15), ('video', 16), ('columns', 20), ('card_grid', 28)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 240, 'required': False}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('label', 3), ('page', 4), ('url', 5)]], {'label': 'Call to action', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('background', 2), ('cta', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'document-link', 'ol', 'ul', 'hr', 'blockquote', 'image']}), 9: ('wagtail.blocks.ListBlock', (2,), {}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('images', 9), ('autoplay', 10)]], {}), 12: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 8)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('items', 13), ('allow_multiple_open', 14)]], {}), 16: ('apps.pages.blocks.VideoEmbedBlock', (), {}), 17: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', 'Two columns'), ('3', 'Three columns')]}), 18: ('wagtail.blocks.StreamBlock', [[('rich_text', 8), ('image', 2), ('collapse', 15), ('video', 16)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {}), 20: ('wagtail.blocks.StructBlock', [[('layout', 17), ('columns', 19)]], {}), 21: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2'), ('3', '3'), ('4', '4')]}), 22: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 23: ('wagtail.blocks.TextBlock', (), {'required': False}), 24: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 25: ('wagtail.blocks.StructBlock', [[('label', 3), ('page', 4), ('url', 5)]], {'required': False}), 26: ('wagtail.blocks.StructBlock', [[('image', 2), ('title', 0), ('subtitle', 22), ('text', 23), ('price', 24), ('link', 25)]], {}), 27: ('wagtail.blocks.ListBlock', (26,), {}), 28: ('wagtail.blocks.StructBlock', [[('columns', 21), ('cards', 27)]], {})})),
            ],
            options={
                'verbose_name': 'Page',
            },
            bases=(wagtail_headless_preview.models.HeadlessMixin, 'wagtailcore.page'),
        ),
    ]
