# Generated by Django 6.1.1 on 2026-09-08 12:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_wrap_rich_text_in_struct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 7),
                    ("rich_text", 12),
                    ("image", 2),
                    ("image_slider", 15),
                    ("collapse", 19),
                    ("video", 20),
                    ("columns", 24),
                    ("card_grid", 32),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 120}),
                    1: ("wagtail.blocks.CharBlock", (), {"max_length": 240, "required": False}),
                    2: ("wagtail.images.blocks.ImageBlock", [], {}),
                    3: ("wagtail.blocks.CharBlock", (), {"max_length": 60, "required": False}),
                    4: ("wagtail.blocks.PageChooserBlock", (), {"required": False}),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"label": "External URL", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 3), ("page", 4), ("url", 5)]],
                        {"label": "Call to action", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 0), ("subheading", 1), ("background", 2), ("cta", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "ol",
                                "ul",
                                "hr",
                                "blockquote",
                                "image",
                            ]
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("default", "Default"),
                                ("ink", "Light"),
                                ("accent", "Gold"),
                                ("sage", "Sage"),
                            ],
                            "label": "Text color",
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("sm", "Small"), ("md", "Normal"), ("lg", "Large")],
                            "label": "Font size",
                        },
                    ),
                    11: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("tight", "Tight"),
                                ("normal", "Normal"),
                                ("relaxed", "Relaxed"),
                            ],
                            "label": "Line spacing",
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 8), ("color", 9), ("size", 10), ("line_height", 11)]],
                        {},
                    ),
                    13: ("wagtail.blocks.ListBlock", (2,), {}),
                    14: ("wagtail.blocks.BooleanBlock", (), {"default": True, "required": False}),
                    15: ("wagtail.blocks.StructBlock", [[("images", 13), ("autoplay", 14)]], {}),
                    16: ("wagtail.blocks.StructBlock", [[("title", 0), ("content", 8)]], {}),
                    17: ("wagtail.blocks.ListBlock", (16,), {}),
                    18: ("wagtail.blocks.BooleanBlock", (), {"default": False, "required": False}),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("items", 17), ("allow_multiple_open", 18)]],
                        {},
                    ),
                    20: ("apps.pages.blocks.VideoEmbedBlock", (), {}),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("2", "Two columns"), ("3", "Three columns")]},
                    ),
                    22: (
                        "wagtail.blocks.StreamBlock",
                        [[("rich_text", 12), ("image", 2), ("collapse", 19), ("video", 20)]],
                        {},
                    ),
                    23: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {
                            "help_text": "Add one list item per column; put the column's content inside that item.",
                            "max_num": 3,
                            "min_num": 2,
                        },
                    ),
                    24: ("wagtail.blocks.StructBlock", [[("layout", 21), ("columns", 23)]], {}),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("2", "2"), ("3", "3"), ("4", "4")]},
                    ),
                    26: ("wagtail.blocks.CharBlock", (), {"max_length": 120, "required": False}),
                    27: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    28: ("wagtail.blocks.CharBlock", (), {"max_length": 40, "required": False}),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 3), ("page", 4), ("url", 5)]],
                        {"required": False},
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("image", 2),
                                ("title", 0),
                                ("subtitle", 26),
                                ("text", 27),
                                ("price", 28),
                                ("link", 29),
                            ]
                        ],
                        {},
                    ),
                    31: ("wagtail.blocks.ListBlock", (30,), {}),
                    32: ("wagtail.blocks.StructBlock", [[("columns", 25), ("cards", 31)]], {}),
                },
            ),
        ),
    ]
