# Generated by Django 6.1.1 on 2026-09-08 12:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_columns_block_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 7), ('rich_text', 13), ('image', 2), ('image_slider', 16), ('collapse', 20), ('video', 21), ('columns', 25), ('card_grid', 33)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 240, 'required': False}), 2: ('wagtail.images.blocks.ImageBlock', [], {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 60, 'required': False}), 4: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'label': 'External URL', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('label', 3), ('page', 4), ('url', 5)]], {'label': 'Call to action', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('background', 2), ('cta', 6)]], {}), 8: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'document-link', 'ol', 'ul', 'hr', 'blockquote', 'image']}), 9: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('ink', 'Light'), ('accent', 'Gold'), ('sage', 'Sage')], 'label': 'Text color'}), 10: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Small'), ('md', 'Normal'), ('lg', 'Large')], 'label': 'Font size'}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('tight', 'Tight'), ('normal', 'Normal'), ('relaxed', 'Relaxed')], 'label': 'Line spacing'}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')], 'label': 'Alignment'}), 13: ('wagtail.blocks.StructBlock', [[('text', 8), ('color', 9), ('size', 10), ('line_height', 11), ('align', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (2,), {}), 15: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('images', 14), ('autoplay', 15)]], {}), 17: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 8)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('items', 18), ('allow_multiple_open', 19)]], {}), 21: ('apps.pages.blocks.VideoEmbedBlock', (), {}), 22: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', 'Two columns'), ('3', 'Three columns')]}), 23: ('wagtail.blocks.StreamBlock', [[('rich_text', 13), ('image', 2), ('collapse', 20), ('video', 21)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'help_text': "Add one list item per column; put the column's content inside that item.", 'max_num': 3, 'min_num': 2}), 25: ('wagtail.blocks.StructBlock', [[('layout', 22), ('columns', 24)]], {}), 26: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2'), ('3', '3'), ('4', '4')]}), 27: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 28: ('wagtail.blocks.TextBlock', (), {'required': False}), 29: ('wagtail.blocks.CharBlock', (), {'max_length': 40, 'required': False}), 30: ('wagtail.blocks.StructBlock', [[('label', 3), ('page', 4), ('url', 5)]], {'required': False}), 31: ('wagtail.blocks.StructBlock', [[('image', 2), ('title', 0), ('subtitle', 27), ('text', 28), ('price', 29), ('link', 30)]], {}), 32: ('wagtail.blocks.ListBlock', (31,), {}), 33: ('wagtail.blocks.StructBlock', [[('columns', 26), ('cards', 32)]], {})}),
        ),
    ]
