# Generated by Django 6.1.1 on 2026-09-07 20:53

import django.core.validators
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Show the music player on the site.')),
                ('volume', models.PositiveSmallIntegerField(default=40, validators=[django.core.validators.MaxValueValidator(100)])),
                ('tracks', wagtail.fields.StreamField([('track', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Defaults to the file title.', 'max_length': 120, 'required': False}), 1: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'label': 'Audio file (mp3/ogg/m4a)'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('file', 1)]], {})})),
            ],
            options={
                'verbose_name': 'Music',
            },
        ),
    ]
