from .base import *  # noqa: F403

DEBUG = False
CSRF_TRUSTED_ORIGINS = [BACKEND_PUBLIC_URL]  # noqa: F405
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
