name: Develop

on:
  push:
    branches: [develop]
  workflow_dispatch:

concurrency:
  group: deploy-develop
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: develop
    secrets: inherit
    permissions:
      contents: read
      packages: write
